name: Build and publish

on: push

jobs:
    build:
        name: Build for ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      artifact_name: sqlite3-stats.so
      
        steps:
            - uses: actions/checkout@v2

            - run: mkdir dist

            - name: Build for Linux
              if: matrix.os == 'ubuntu-latest'
              run: gcc -fPIC -lm -shared WindowsFormsApp3.sln -o dist/sqlite3-stats.so

            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: dist/${{ matrix.artifact_name }}
                  asset_name: ${{ matrix.asset_name }}
                  tag: ${{ github.ref }}
