name: Create Archive
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.2
      with:
        type: 'zip'
        filename: 'release.zip'
        
